version: '3.9'
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ProyectoAMY
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 44639249
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./bd/ProyectoAMY.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    build: .
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__SqliteConexion=Server=host.docker.internal;Database=ProyectoAMY;Username=postgres;Password=44639249;
    depends_on:
      - postgres

volumes:
  pgdata:
